### ISSUE TITLE
Unblocked Games

### ISSUE THREAD

**Issue by BloxburgPro** [Sushi8756/Cookie-Clicker-Source-Code#2]
Hello, My school is very strict, and the website version will not work, how does the download html version work? 
Also, can it be embed into Google sites?

**Comment by Sushi8756** [comment]
All you have to do is download the release on Github. If it is blocked on Google, download it on a different device to a USB and transfer to your school computer, or put it on a Google drive.
You should be able to embed it, but it will still be blocked at school.

**Comment by BloxburgPro** [comment]
Okay, Two Questions, one my school is now becoming very strict and is this GitHub download version one- hundred percent block proof? Two, do you have to download zip, unzip, then add to drive?

**Comment by Sushi8756** [comment]
The downloaded html should be 100% block proof.
You should download zip, add to drive, then when you download it on your school computer from the drive, then unzip.

**Comment by BloxburgPro** [comment]
Hello, so I downloaded the file on my IPad, then transferred to ChromBook then unzipped what do I do now?
(I used to do this often for games, and now forgot)

**Comment by Sushi8756** [comment]
Now all you have to do is open index.html with Google or a different browser.

**Comment by BloxburgPro** [comment]
Then what?

**Comment by Sushi8756** [comment]
Then you play it. 
Idk what else to tell you.

**Comment by BloxburgPro** [comment]
Thank you, I will give it it another look, I am good with computers, so this should be easier then what it is.

**Comment by BloxburgPro** [comment]
Is this on Google, or on your desktop? because what I can find would make the application go on your desktop not on a Google link and my school computer is a ChromeBook

**Comment by Sushi8756** [comment]
You have to find the index.html file with a file browser or something, then open it. It should open with Google. If it doesn't, right click it, then open with if you can and select google.
Idk how to use chrome book so you might have to figure this out by yourself.

**Comment by BloxburgPro** [comment]
Good Job On It! it worked thank you!

**Comment by Sushi8756** [comment]
No problem! I'm glad you enjoy it!
